import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errs: string[] = [];
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
p.on('pageerror', (e) => errs.push(String(e)));
await p.goto('http://localhost:4173/?fast=1');
await p.getByRole('button', { name: /Level 1 — Meet Hans/ }).click();
await p.getByRole('button', { name: 'Train the network →' }).click();
await p.screenshot({ path: '/tmp/train0.png' });
await p.getByRole('button', { name: 'Start training' }).click();
await p.waitForTimeout(3000);
await p.screenshot({ path: '/tmp/train1.png' });
await p.getByRole('heading', { name: 'Three exams, one confession' }).waitFor({ timeout: 180000 });
await p.screenshot({ path: '/tmp/exam.png' });
await p.getByRole('button', { name: /Where was it looking/ }).click();
await p.waitForTimeout(500);
await p.screenshot({ path: '/tmp/heat.png' });
await p.getByRole('button', { name: /Mostly at the background/ }).click();
await p.getByRole('button', { name: /Deliver the verdict/ }).click();
await p.screenshot({ path: '/tmp/verdict.png' });
await p.getByRole('button', { name: /Level 3 — fix the data/ }).click();
await p.screenshot({ path: '/tmp/l3.png' });
await p.goto('http://localhost:4173/#/lab');
await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/lab.png' });
await p.goto('http://localhost:4173/#/teacher');
await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/teacher.png' });
console.log('errors:', errs.slice(0, 10));
await b.close();
